### ISSUE TITLE
Licensing info

### ISSUE THREAD

**Issue by fpesari** [brummer10/MetalTone#2]
Hello,

is this plugin licenseless for a reason? I wanted to package it for openSUSE but cannot do it without licensing info.

**Comment by brummer10** [comment]
Hi
I've just forgotten to add it. It's released under the BSD Zero Clause License, while some files been under the GPL 3.0 or later. Those have the licencing info in the file itself.

**Comment by fpesari** [comment]
Thanks @brummer10 ! Will make a package for openSUSE soon.

I noticed that @falkTX made a small commit, pinging him for his OK, too (just because licenses can't be retroactive).

**Comment by falkTX** [comment]
your project cannot be BSD licensed if it uses GPL code.
the end result needs to be GPL compatible. you can have specific code be BSD licensed, but the final binary has to be GPL or compatible.

**Comment by brummer10** [comment]
Yes. That's how it is. All files which don't state otherwise, been under the BSD Zero Clause License. The project contain files under the gpl 3.0+, so the resulting binary is under the gpl 3.0+. But, that doesn't mean that the complete project have to be under the gpl 3.0+.  BSD Zero Clause License is absolutely compatible with gpl 3.0+, so it's allowed to do static linking. All files which don't state otherwise, been under the BSD Zero Clause License.

**Comment by fpesari** [comment]
Yeah @falkTX , the GPL stuff is correct but I asked you if you can explicitly give your OK to the 0BSD for your commit https://github.com/brummer10/MetalTone/commit/3321e9df7093f722075c38b5106e3e250e094d95 since previously there was no license file. Boring legal(ish) stuff but necessary to avoid controversies :smile:

**Comment by falkTX** [comment]
Making the project BSD licensed is misleading though, since no one can make binaries out of it being "just" BSD, those are GPL instead.
So it is extremely weird that a BSD project generates GPL binaries, and causes confusion to users and packagers. Any packager looking at this repo will first assume the resulting package is BSD, when in fact is not.

I advise you to change this.

**Comment by brummer10** [comment]
I was not able to find a licence text to include on github to make it gpl 3.0+. Do you've a link for me? I could then implement the BSD Zero Clause License file wise and put the project under the gpl 3.0+ 
Github unfortunately only provide licence files for gpl 2.0/3.0 only which is in no way suitable.

**Comment by falkTX** [comment]
gplv3+ is gpl3 license, there is nothing in the license itself that will say "or later".
the "or later" will be on your readme and code

**Comment by brummer10** [comment]
So how is that less confusing than keep the project under BSD Zero Clause License? In both cases you've to check the individual source files to get the 'real' licence. As stated above, the BSD Zero Clause License is absolutely compatible to link with gpl sources. If there will be ever a licence text stated as gpl 3.0+ I'll add it to this project . . .

**Comment by falkTX** [comment]
BSD is compatible with GPL in the sense that it can be "upgraded" to GPL, but not vice-versa. You cannot take GPL code and relicense it as BSD, but you can take BSD and relicense it as GPL.
That is how far they are compatible.
Placing your project as BSD makes this confusing because one assumes the whole source to be BSD compatible, which is not the case.

The GPL "or later" is just an extra technicality. For all intents and purposes a GPLvX+ project is licensed under GPLvX, the "or later" is mostly for those that care for compatibility with other and future GPL licenses. The license is "GPLvX", a "GPLvX+" is not and never will be a valid license.
You cannot license a project under something that does not exist yet (such as GPLv4).
So projects typically just include a statement such as:

>    Copyright (C) \<year>  \<name of author>
>
>    This program is free software: you can redistribute it and/or modify
>    it under the terms of the GNU General Public License as published by
>    the Free Software Foundation, either version 2 of the License, or
>    (at your option) any later version.
>
>    This program is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU General Public License for more details.

Then the license file will be specifically GPLv2 or GPLv3.

**Comment by brummer10** [comment]
So okay, I've changed the Project License to GPL v3.0 and added a LICENSE.text file to inform that it means any later, and that all files which didn't contain a License info been released under the 0BSD License. 
Hope that suite all needs.

**Comment by falkTX** [comment]
That should be fine in theory I think.
It is common now for new projects to go with SPDX identifiers on source files. They are short (so dont waste a lot of code lines) and to the point, describing exactly what the license is for each file.
https://spdx.dev/ids/#how has details for that
